# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [2]:
from scipy import stats 
import numpy as np

In [3]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [8]:
t_statistic, p_value = stats.ttest_1samp(GPU1,0);
print("P_value ",p_value);

P_value  7.228892044970457e-15


As p_value is exteremely less - Alternate is true

In [11]:
mean = GPU1.mean()
std = GPU1.std()

1.1352924243950933

## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [20]:
#shape of both the GPUs ---
S1= GPU1.shape
S2= GPU2.shape
print(S1,S2)
t_statistics, p_value = stats.ttest_ind(GPU1,GPU2)
p_value

(15,) (15,)


0.013794282041452725

The p value is extremely less than the alpha - hence reject the null -- alternate is true.

## Question 3

He is trying a third GPU - GPU3.

In [21]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [22]:
t_statistics, p_value = stats.ttest_ind(GPU1,GPU3)
p_value

0.14509210993138993

Null Hypothesis : There is no significant difference between speeds of GPU1 and GPU3 

Alternate Hypothesis : There is a significant difference between speeds of GPU1 and GPU3 

As p value is much greater than the alpha - 0.05 , hence we do not have any significant proof for rejecting the null - which  implies that There is no significant difference between speeds of GPU1 and GPU3

## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [24]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [25]:
#as data sets are given normally distributed hence, mean levene test is being used 
stats.levene(e1,e2,e3)

LeveneResult(statistic=2.6741725711150446, pvalue=0.12259792666001798)

As p-value is sgnificantly higher than alpha - hence we cannot reject the null hypothesis that all input samples are from populations with equal variances.

## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [27]:
F, p = stats.f_oneway(e1, e2, e3)
print(F,p)

2.51357622845924 0.13574644501798466


As the p value  is isgnificantly higher than alpha hence we can say that e1, e2 ,e3 have significantly different population mean and hence are different from each other 

## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer: 

answer here : A type I error (false-positive) occurs if an investigator rejects a null hypothesis that is actually true in the population; a type II error (false-negative) occurs if the investigator fails to reject a null hypothesis that is actually false in the population.

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


answer here
Null Hypothesis H0: The mean time is 4.5 minutes.

Alternative Hypothesis : The mean time is different from 4.5 mins and is not equal to 4.5 mins.

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [28]:
import numpy as np
# Here d1 to d6 are the number of dice and four values in each dice represents value of dice for player 1 to player 4

d1 = [1, 6, 3, 4]
d2 = [2, 5, 1, 3]
d3 = [4, 2, 3, 1]
d4 = [3, 4, 1, 2]
d5 = [1, 6, 3, 5]
d6 = [3, 2, 2, 1]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [30]:
chi_sq_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(dice)
print('chi_sq_Stat',chi_sq_Stat)
print ('p_value',p_value)
print('degree of freedom',deg_freedom)
print('contigency',exp_freq)


chi_sq_Stat 11.445004959326388
p_value 0.720458335452983
degree of freedom 15
contigency [[2.88235294 5.14705882 2.67647059 3.29411765]
 [2.26470588 4.04411765 2.10294118 2.58823529]
 [2.05882353 3.67647059 1.91176471 2.35294118]
 [2.05882353 3.67647059 1.91176471 2.35294118]
 [3.08823529 5.51470588 2.86764706 3.52941176]
 [1.64705882 2.94117647 1.52941176 1.88235294]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [35]:
z_scores = stats.zscore(dice,ddof=1)
z_scores

array([[-1.10096377,  0.99917458,  0.84757938,  0.81649658],
       [-0.27524094,  0.45417026, -1.18661113,  0.20412415],
       [ 1.37620471, -1.18084268,  0.84757938, -1.02062073],
       [ 0.55048188, -0.09083405, -1.18661113, -0.40824829],
       [-1.10096377,  0.99917458,  0.84757938,  1.42886902],
       [ 0.55048188, -1.18084268, -0.16951588, -1.02062073]])

In [36]:
p_values_1 = stats.norm.sf(abs(z_scores)) #one-sided
p_values_1


array([[0.13545621, 0.15885506, 0.19833613, 0.20710809],
       [0.39156557, 0.32485314, 0.11769052, 0.41912824],
       [0.08437913, 0.11883261, 0.19833613, 0.15371708],
       [0.29099445, 0.46381223, 0.11769052, 0.3415457 ],
       [0.13545621, 0.15885506, 0.19833613, 0.07652094],
       [0.29099445, 0.11883261, 0.43269544, 0.15371708]])

In [37]:
p_values_1.mean()

0.2203211987239302

## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [38]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

Null Hypothesis : No signiifcant change in weight before and after 

Alternate : There is a significant change in weight before and after

In [46]:
after.mean()

98.18866452795847

In [41]:
before.mean()

99.41135008044895

In [44]:
#As size for both the samples are same -- scipy.stats.ttest_rel to calculate the T-test on TWO RELATED samples of scores.
t_statistic, p_value  =  stats.ttest_rel(after, before )
print('P Value' ,p_value)  

P Value 1.4426769310436869e-08


As p-value is significantly low hence there is significant change in weight